config/routes.rb
# frozen_string_literal: true

Thredded::Engine.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :theme_preview, only: [:show], path: 'theme-preview' if %w[development test].include? Rails.env

  page_constraint = { page: /[1-9]\d*/ }

  scope path: 'private-topics' do
    resource :read_state, only: [:update], as: :mark_all_private_topics_read
    resource :private_topic, only: [:new], path: '' do
      post :preview, on: :new, controller: 'private_topic_previews'
    end
    resources :private_topics, except: %i[new show], path: '' do
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint
      end
      resources :private_posts, path: '', except: %i[index show] do
        post :preview, on: :new, controller: 'private_post_previews'
        resource :preview, only: [:update], controller: 'private_post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  scope only: [:show], constraints: { id: Thredded.routes_id_constraint } do
    resources :private_post_permalinks, path: 'private-posts'
    resources :post_permalinks, path: 'posts'
  end

  resources :autocomplete_users, only: [:index], path: 'autocomplete-users'

  constraints(->(req) { req.env['QUERY_STRING'].include? 'q=' }) do
    get '/' => 'topics#search', as: :messageboards_search
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  scope path: 'admin' do
    resources :messageboard_groups, only: %i[new create]
    scope controller: :moderation, path: 'moderation' do
      scope constraints: page_constraint do
        get '(/page-:page)', action: :pending, as: :pending_moderation
        get '/history(/page-:page)', action: :history, as: :moderation_history
        get '/users(/page-:page)', action: :users, as: :users_moderation
        get '/users/:id(/page-:page)', action: :user, as: :user_moderation
        get '/activity(/page-:page)', action: :activity, as: :moderation_activity
      end
      post '', action: :moderate_post, as: :moderate_post
      post '/user/:id', action: :moderate_user, as: :moderate_user
    end
  end

  resource :preferences, only: %i[edit update], as: :global_preferences
  resource :messageboard, path: 'messageboards', only: [:new]
  resources :messageboards, only: %i[edit update]
  resources :messageboards, only: %i[index create], path: '' do
    resource :preferences, only: %i[edit update]
    resource :topic, path: 'topics', only: [:new] do
      post :preview, on: :new, controller: 'topic_previews'
    end
    resources :topics, path: '', except: %i[index new show] do
      collection do
        get '(page-:page)', action: :index, as: '', constraints: page_constraint
        get '/category/:category_id', action: :category, as: :categories
      end
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint

        # match (un)follow via get as well so that redirecting back to it after sign in works.
        match 'follow', via: %i[post get]
        match 'unfollow', via: %i[post get]
      end
      resources :posts, except: %i[index show], path: '' do
        post :preview, on: :new, controller: 'post_previews'
        resource :preview, only: [:update], controller: 'post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  root to: 'messageboards#index'
end

app/models/concerns/thredded/content_moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Moderation state of a piece of content, such as a Thredded::Topic or a Thredded::Post.
  # Requires an integer moderation_state column, a user_id column, and a user_detail association on the including class.
  # @api private
  module ContentModerationState
    extend ActiveSupport::Concern
    include Thredded::ModerationState

    included do
      before_validation :set_default_moderation_state, on: :create

      scope :moderation_state_visible_to_all, -> { where(visible_to_all_arel_node) }

      scope :moderation_state_visible_to_user, (lambda do |user|
        visible = visible_to_all_arel_node
        # @type [Arel::Table]
        table = arel_table
        if user && !user.thredded_anonymous?
          # Own content
          visible = visible.or(table[:user_id].eq(user.id))
          # Content that one can moderate
          moderatable_messageboard_ids = user.thredded_can_moderate_messageboards.map(&:id)
          if moderatable_messageboard_ids.present?
            visible = visible.or(table[:messageboard_id].in(moderatable_messageboard_ids))
          end
        end
        where(visible)
      end)

      # @return [Arel::Nodes::Node]
      # @api private
      def self.visible_to_all_arel_node
        if Thredded.content_visible_while_pending_moderation
          # All non-blocked content
          arel_table[:moderation_state].not_eq(moderation_states[:blocked])
        else
          # Only approved content
          arel_table[:moderation_state].eq(moderation_states[:approved])
        end
      end
    end

    # Whether this is visible to anyone based on the moderation state.
    def moderation_state_visible_to_all?
      if Thredded.content_visible_while_pending_moderation
        !blocked?
      else
        approved?
      end
    end

    # Whether this is visible to the given user based on the moderation state.
    def moderation_state_visible_to_user?(user)
      moderation_state_visible_to_all? ||
        (!user.thredded_anonymous? &&
          (user_id == user.id || user.thredded_can_moderate_messageboards.map(&:id).include?(messageboard_id)))
    end

    private

    def set_default_moderation_state
      self.moderation_state ||= user_detail.moderation_state
    end
  end
end

app/models/concerns/thredded/friendly_id_reserved_words_and_pagination.rb
# frozen_string_literal: true

require 'set'
module Thredded
  # Excludes pagination routes in addition to the given list of reserved words.
  class FriendlyIdReservedWordsAndPagination
    PAGINATION_PATTERN = /\Apage-\d+\z/i

    def initialize(words = [])
      @words = Set.new(words)
    end

    def include?(slug)
      @words.include?(slug) || slug =~ PAGINATION_PATTERN
    end
  end
end

app/models/concerns/thredded/moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Defines a moderation_state enum
  # Requires an integer moderation_state column on the including class.
  module ModerationState
    extend ActiveSupport::Concern

    included do
      enum moderation_state: %i[pending_moderation approved blocked]
      validates :moderation_state, presence: true
    end
  end
end

app/models/concerns/thredded/notifier_preference.rb
# frozen_string_literal: true

module Thredded
  module NotifierPreference
    extend ActiveSupport::Concern

    included do
      delegate :human_name, to: :notifier, prefix: true

      def self.detect_or_default(prefs, notifier)
        (prefs && prefs.find { |pref| pref.notifier_key == notifier.key }) || default(notifier)
      end
    end

    def notifier
      @notifier ||= Thredded.notifiers.find { |notifier| notifier.key == notifier_key }
    end
  end
end

app/models/concerns/thredded/post_common.rb
# frozen_string_literal: true

module Thredded
  # @abstract Classes that include this module are expected to implement {#readers}.
  # @!method readers
  #     @abstract
  #     @return [ActiveRecord::Relation<Thredded.user_class>] users from that can read this post.
  module PostCommon
    extend ActiveSupport::Concern

    included do
      paginates_per 50

      delegate :email, to: :user, prefix: true, allow_nil: true

      validates :content, presence: true

      scope :order_oldest_first, -> { order(created_at: :asc, id: :asc) }
      scope :order_newest_first, -> { order(created_at: :desc, id: :desc) }

      before_validation :ensure_user_detail, on: :create
    end

    def avatar_url
      Thredded.avatar_url.call(user)
    end

    def calculate_page(postable_posts, per_page)
      1 + postable_posts.where(postable_posts.arel_table[:created_at].lt(created_at)).count / per_page
    end

    # @param view_context [Object] the context of the rendering view.
    # @return [String] formatted and sanitized html-safe post content.
    def filtered_content(view_context, users_provider: ->(names) { readers_from_user_names(names) }, **options)
      Thredded::ContentFormatter.new(view_context, users_provider: users_provider, **options).format_content(content)
    end

    def first_post_in_topic?
      postable.first_post == self
    end

    # @return [ActiveRecord::Relation<Thredded.user_class>] users from the list of user names that can read this post.
    # @api private
    def readers_from_user_names(user_names)
      DbTextSearch::CaseInsensitive
        .new(readers, Thredded.user_name_column)
        .in(user_names)
    end

    # Marks all the posts from the given one as unread for the given user
    # @param user [Thredded.user_class]
    # @param page [Integer]
    def mark_as_unread(user, page)
      if previous_post.nil?
        read_state = postable.user_read_states.find_by(user_id: user.id)
        read_state.destroy if read_state
      else
        read_state = postable.user_read_states.create_with(
          read_at: previous_post.created_at,
          page: page
        ).find_or_create_by(user_id: user.id)
        read_state.update_columns(read_at: previous_post.created_at, page: page)
      end
    end

    def previous_post
      @previous_post ||= postable.posts.order_newest_first.find_by('created_at < ?', created_at)
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end
  end
end

app/models/concerns/thredded/search_parser.rb
# frozen_string_literal: true

module Thredded
  class SearchParser
    def initialize(query)
      @query = query
      @keywords = %w[in by order]
    end

    def parse
      parsed_input = parse_keywords
      parsed_input['text'] = parse_text
      parsed_input
    end

    def parse_keywords
      found_terms_hash = {}

      @keywords.each do |keyword|
        regex = Regexp.new(keyword + '\s*:\s*\w+', Regexp::IGNORECASE)
        keyword_scan = @query.scan(regex)
        @query = @query.gsub(regex, '')

        next if keyword_scan.blank?
        keyword_scan.each do |term|
          found_terms_hash[keyword] ||= []
          found_terms_hash[keyword] << term.delete(' ').split(':')[1]
        end
      end

      found_terms_hash
    end

    def parse_text
      regex = Regexp.new('\"[^"]*\"')
      found_terms = @query.scan(regex)
      @query = @query.sub(regex, '')
      found_terms.concat(@query.split(/\s+/))
    end
  end
end

app/models/concerns/thredded/topic_common.rb
# frozen_string_literal: true

module Thredded
  module TopicCommon
    extend ActiveSupport::Concern
    included do
      paginates_per 50 if respond_to?(:paginates_per)

      belongs_to :last_user,
                 class_name: Thredded.user_class_name,
                 foreign_key: 'last_user_id',
                 **(Thredded.rails_gte_51? ? { optional: true } : {})

      scope :order_recently_posted_first, -> { order(last_post_at: :desc, id: :desc) }
      scope :on_page, ->(page_num) { page(page_num) }

      validates :hash_id, presence: true, uniqueness: true
      validates :posts_count, numericality: true

      before_validation do
        self.hash_id = SecureRandom.hex(10) if hash_id.nil?
      end

      delegate :name, :name=, :email, :email=, to: :user, prefix: true

      before_validation :ensure_user_detail, on: :create
    end

    def user
      super || Thredded::NullUser.new
    end

    def last_user
      super || Thredded::NullUser.new
    end

    def private?
      !public?
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end

    module ClassMethods
      # @param user [Thredded.user_class]
      # @return [ActiveRecord::Relation]
      def unread(user)
        topics      = arel_table
        reads_class = reflect_on_association(:user_read_states).klass
        reads       = reads_class.arel_table
        joins(topics.join(reads, Arel::Nodes::OuterJoin)
                .on(topics[:id].eq(reads[:postable_id]).and(reads[:user_id].eq(user.id))).join_sources)
          .merge(reads_class.where(reads[:id].eq(nil).or(reads[:read_at].lt(topics[:last_post_at]))))
      end

      private

      # @param user [Thredded.user_class]
      # @return [ByPostableLookup]
      def read_states_by_postable_hash(user)
        read_states = reflect_on_association(:user_read_states).klass
          .where(user_id: user.id, postable_id: current_scope.map(&:id))
        Thredded::TopicCommon::CachingHash.from_relation(read_states)
      end

      public

      # @param user [Thredded.user_class]
      # @return [Array<[TopicCommon, UserTopicReadStateCommon]>]
      def with_read_states(user)
        null_read_state = Thredded::NullUserTopicReadState.new
        return current_scope.zip([null_read_state]) if user.thredded_anonymous?
        read_states_by_postable = read_states_by_postable_hash(user)
        current_scope.map do |postable|
          [postable, read_states_by_postable[postable] || null_read_state]
        end
      end
    end

    class CachingHash < Hash
      def self.from_relation(postable_relation)
        self[postable_relation.map { |related| [related.postable_id, related] }]
      end

      # lookup related item by postable and set the inverse lookup
      def [](postable)
        super(postable.id).tap { |related| related.postable = postable if related }
      end
    end
  end
end

app/models/concerns/thredded/topics_search.rb
# frozen_string_literal: true

module Thredded
  class TopicsSearch
    def initialize(query, scope)
      @terms = Thredded::SearchParser.new(query).parse
      @scope = scope

      @search_categories = @search_users = @search_text = nil
    end

    # @return [ActiveRecord::Relation<Thredded::Topic>]
    def search
      if categories.present?
        @scope = @scope.joins(:topic_categories).merge(Thredded::TopicCategory.where(category_id: categories))
      end
      if text.present? || users.present?
        [search_topics, search_posts].compact.reduce(:union)
      else
        @scope
      end
    end

    protected

    def search_topics
      scope = @scope
      scope = @scope.where(user_id: users) if users.present?
      scope = DbTextSearch::FullText.new(scope, :title).search(text) if text.present?
      scope
    end

    def search_posts
      posts_scope = Thredded::Post
      posts_scope = posts_scope.where(user_id: users) if users.present?
      posts_scope = DbTextSearch::FullText.new(posts_scope, :content).search(text) if text.present?
      @scope.joins(:posts).merge(posts_scope)
    end

    def categories
      @search_categories ||=
        if @terms['in'].present?
          DbTextSearch::CaseInsensitive
            .new(Category, :name)
            .in(@terms['in']).pluck(:id)
        else
          []
        end
    end

    def users
      @search_users ||=
        if @terms['by']
          DbTextSearch::CaseInsensitive
            .new(Thredded.user_class, Thredded.user_name_column)
            .in(@terms['by']).pluck(:id)
        else
          []
        end
    end

    # @return [Array<String>]
    def text
      @terms['text']
    end
  end
end

app/models/concerns/thredded/user_topic_read_state_common.rb
# frozen_string_literal: true

module Thredded
  module UserTopicReadStateCommon
    extend ActiveSupport::Concern
    included do
      extend ClassMethods
      validates :user_id, uniqueness: { scope: :postable_id }
    end

    # @return [Boolean]
    def read?
      postable.last_post_at <= read_at
    end

    # @param post [Post or PrivatePost]
    # @return [Boolean]
    def post_read?(post)
      post.created_at <= read_at
    end

    module ClassMethods
      # @param user_id [Integer]
      # @param topic_id [Integer]
      # @param post [Thredded::PostCommon]
      # @param post_page [Integer]
      def touch!(user_id, topic_id, post, post_page)
        # TODO: Switch to upsert once Travis supports PostgreSQL 9.5.
        # Travis issue: https://github.com/travis-ci/travis-ci/issues/4264
        # Upsert gem: https://github.com/seamusabshere/upsert
        state = find_or_initialize_by(user_id: user_id, postable_id: topic_id)
        fail ArgumentError, "expected post_page >= 1, given #{post_page.inspect}" if post_page < 1
        return unless !state.read_at? || state.read_at < post.created_at
        state.update!(read_at: post.created_at, page: post_page)
      end

      def read_on_first_post!(user, topic)
        create!(user: user, postable: topic, read_at: Time.zone.now, page: 1)
      end
    end
  end
end

app/models/thredded/category.rb
# frozen_string_literal: true

module Thredded
  class Category < ActiveRecord::Base
    extend FriendlyId
    belongs_to :messageboard
    has_many :topic_categories
    has_many :topics, through: :topic_categories
    friendly_id :name, use: %i[history scoped], scope: :messageboard

    validates :name, presence: true
    validates :messageboard_id, presence: true

    def normalize_friendly_id(input)
      Thredded.slugifier.call(input.to_s)
    end
  end
end

app/models/thredded/null_user_topic_read_state.rb
# frozen_string_literal: true

module Thredded
  class NullUserTopicReadState
    def page
      1
    end

    def read?
      false
    end

    def post_read?(_post)
      false
    end
  end
end

app/views/thredded/messageboards/_form.html.erb
<%= form_for messageboard, html: { class: 'thredded--form' } do |f| %>
    <ul class="thredded--form-list">
      <li>
        <%= f.label t('thredded.messageboard.form.title_label') %>
        <%= f.text_field :name, required: true %>
      </li>
      <li>
        <%= f.label t('thredded.messageboard.form.description_label') %>
        <%= f.text_field :description %>
      </li>
      <li>
        <%= f.label t('thredded.messageboard.form.messageboard_group_id_label') %>
        <%= f.collection_select :messageboard_group_id, Thredded::MessageboardGroup.all, :id, :name,
                                include_blank: t('thredded.messageboard.form.no_group') %>
      </li>
      <li>
        <%= f.label :locked do %>
            <%= f.check_box :locked %> <%= t 'thredded.messageboard.form.locked_label' %>
        <% end %>
      </li>

      <li>
        <%= f.submit @messageboard.persisted? ? t('thredded.messageboard.update') : t('thredded.messageboard.create'),
                     class: 'thredded--form--submit',
                     'data-disable-with' => @messageboard.persisted? ?
                         t('thredded.messageboard.form.update_btn_submitting') :
                         t('thredded.messageboard.form.create_btn_submitting') %>
      </li>
    </ul>
<% end %>

app/views/thredded/messageboards/_messageboard.html.erb
<% if policy(messageboard).read? %>
  <%= view_hooks.messageboards_index.messageboard.render self, messageboard: messageboard do %>
    <%= link_to messageboard_topics_path(messageboard), class: 'thredded--messageboard' do %>
      <header class="thredded--messageboard--header">
        <h2 class="thredded--messageboard--title"><%= messageboard.name %></h2>
        <%= render 'thredded/messageboards/messageboard_meta', messageboard: messageboard %>
      </header>

      <p class="thredded--messageboard--description"><%= messageboard.description %></p>

      <% if messageboard.last_topic %>
        <p class="thredded--messageboard--byline">
          <%= t 'thredded.messageboard.last_updated_by_html',
                time_ago: time_ago(messageboard.last_topic.last_post_at),
                user: messageboard.last_user.thredded_display_name %>
        </p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/thredded/messageboards/_messageboard_meta.html.erb
<div class="thredded--messageboard--meta">
  <% if messageboard.locked? %>
    <span class="thredded--messageboard--meta--locked"
          title="<%= t('thredded.messageboard.form.locked_notice') %>">
      <%= inline_svg('thredded/lock.svg', class: 'thredded--messageboard--meta--icon') %>
    </span>
  <% end %>
  <h3 class="thredded--messageboard--meta--counts">
    <%= t 'thredded.messageboard.topics_and_posts_counts',
          topics_count: number_with_delimiter(messageboard.topics_count),
          posts_count: number_with_delimiter(messageboard.posts_count) %>
  </h3>
</div>

app/views/thredded/messageboards/edit.html.erb
<% content_for :thredded_page_title, t('thredded.nav.edit_messageboard') %>
<% content_for :thredded_page_id, 'thredded--messageboard-edit' %>
<% content_for :thredded_breadcrumbs do %>
  <ul class="thredded--navigation-breadcrumbs">
    <li class="thredded--navigation-breadcrumbs--item-no-link">
      <%= t('thredded.nav.edit_messageboard') %>
    </li>
  </ul>
<% end %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= render 'form', messageboard: @messageboard %>
  </section>
<% end %>

app/views/thredded/messageboards/index.html.erb
<% content_for :thredded_page_title, t('thredded.messageboard.index.page_title') %>
<% content_for :thredded_page_id, 'thredded--messageboards-index' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>
<%= thredded_page do %>
  <%= view_hooks.messageboards_index.container.render self, groups: @groups do %>
    <section class="thredded--main-section thredded--messageboards">
      <%= view_hooks.messageboards_index.list.render self, groups: @groups do %>
        <% @groups.each do |group| %>
          <% if group.name.present? %>
            <h3 class="thredded--messageboards-group--title"><%= group.name %></h3>
          <% end %>
          <div class="thredded--messageboards-group">
            <%= view_hooks.messageboards_index.group.render self, group: group do %>
              <%= render group.messageboards %>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <div class="thredded--messageboards--actions">
        <% if policy(Thredded::Messageboard.new).create? %>
          <a class="thredded--button" href="<%= new_messageboard_path %>" rel="nofollow">
            <%= t('thredded.messageboard.create') %>
          </a>
        <% end %>
        <% if policy(Thredded::MessageboardGroup.new).create? %>
          <a class="thredded--button" href="<%= new_messageboard_group_path %>" rel="nofollow">
            <%= t('thredded.messageboard_group.create') %>
          </a>
        <% end %>
      </div>
    </section>
  <% end %>
<% end %>

app/views/thredded/messageboards/new.html.erb
<% content_for :thredded_page_title, t('thredded.messageboard.create') %>
<% content_for :thredded_page_id, 'thredded--messageboards-new' %>
<% content_for :thredded_breadcrumbs do %>
  <ul class="thredded--navigation-breadcrumbs">
    <li class="thredded--navigation-breadcrumbs--item-no-link">
      <%= t('thredded.messageboard.create') %>
    </li>
  </ul>
<% end %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= render 'form', messageboard: @messageboard %>
  </section>
<% end %>