config/routes.rb
# frozen_string_literal: true

Thredded::Engine.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :theme_preview, only: [:show], path: 'theme-preview' if %w[development test].include? Rails.env

  page_constraint = { page: /[1-9]\d*/ }

  scope path: 'private-topics' do
    resource :read_state, only: [:update], as: :mark_all_private_topics_read
    resource :private_topic, only: [:new], path: '' do
      post :preview, on: :new, controller: 'private_topic_previews'
    end
    resources :private_topics, except: %i[new show], path: '' do
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint
      end
      resources :private_posts, path: '', except: %i[index show] do
        post :preview, on: :new, controller: 'private_post_previews'
        resource :preview, only: [:update], controller: 'private_post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  scope only: [:show], constraints: { id: Thredded.routes_id_constraint } do
    resources :private_post_permalinks, path: 'private-posts'
    resources :post_permalinks, path: 'posts'
  end

  resources :autocomplete_users, only: [:index], path: 'autocomplete-users'

  constraints(->(req) { req.env['QUERY_STRING'].include? 'q=' }) do
    get '/' => 'topics#search', as: :messageboards_search
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  scope path: 'admin' do
    resources :messageboard_groups, only: %i[new create]
    scope controller: :moderation, path: 'moderation' do
      scope constraints: page_constraint do
        get '(/page-:page)', action: :pending, as: :pending_moderation
        get '/history(/page-:page)', action: :history, as: :moderation_history
        get '/users(/page-:page)', action: :users, as: :users_moderation
        get '/users/:id(/page-:page)', action: :user, as: :user_moderation
        get '/activity(/page-:page)', action: :activity, as: :moderation_activity
      end
      post '', action: :moderate_post, as: :moderate_post
      post '/user/:id', action: :moderate_user, as: :moderate_user
    end
  end

  resource :preferences, only: %i[edit update], as: :global_preferences
  resource :messageboard, path: 'messageboards', only: [:new]
  resources :messageboards, only: %i[edit update]
  resources :messageboards, only: %i[index create], path: '' do
    resource :preferences, only: %i[edit update]
    resource :topic, path: 'topics', only: [:new] do
      post :preview, on: :new, controller: 'topic_previews'
    end
    resources :topics, path: '', except: %i[index new show] do
      collection do
        get '(page-:page)', action: :index, as: '', constraints: page_constraint
        get '/category/:category_id', action: :category, as: :categories
      end
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint

        # match (un)follow via get as well so that redirecting back to it after sign in works.
        match 'follow', via: %i[post get]
        match 'unfollow', via: %i[post get]
      end
      resources :posts, except: %i[index show], path: '' do
        post :preview, on: :new, controller: 'post_previews'
        resource :preview, only: [:update], controller: 'post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  root to: 'messageboards#index'
end

app/models/concerns/thredded/content_moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Moderation state of a piece of content, such as a Thredded::Topic or a Thredded::Post.
  # Requires an integer moderation_state column, a user_id column, and a user_detail association on the including class.
  # @api private
  module ContentModerationState
    extend ActiveSupport::Concern
    include Thredded::ModerationState

    included do
      before_validation :set_default_moderation_state, on: :create

      scope :moderation_state_visible_to_all, -> { where(visible_to_all_arel_node) }

      scope :moderation_state_visible_to_user, (lambda do |user|
        visible = visible_to_all_arel_node
        # @type [Arel::Table]
        table = arel_table
        if user && !user.thredded_anonymous?
          # Own content
          visible = visible.or(table[:user_id].eq(user.id))
          # Content that one can moderate
          moderatable_messageboard_ids = user.thredded_can_moderate_messageboards.map(&:id)
          if moderatable_messageboard_ids.present?
            visible = visible.or(table[:messageboard_id].in(moderatable_messageboard_ids))
          end
        end
        where(visible)
      end)

      # @return [Arel::Nodes::Node]
      # @api private
      def self.visible_to_all_arel_node
        if Thredded.content_visible_while_pending_moderation
          # All non-blocked content
          arel_table[:moderation_state].not_eq(moderation_states[:blocked])
        else
          # Only approved content
          arel_table[:moderation_state].eq(moderation_states[:approved])
        end
      end
    end

    # Whether this is visible to anyone based on the moderation state.
    def moderation_state_visible_to_all?
      if Thredded.content_visible_while_pending_moderation
        !blocked?
      else
        approved?
      end
    end

    # Whether this is visible to the given user based on the moderation state.
    def moderation_state_visible_to_user?(user)
      moderation_state_visible_to_all? ||
        (!user.thredded_anonymous? &&
          (user_id == user.id || user.thredded_can_moderate_messageboards.map(&:id).include?(messageboard_id)))
    end

    private

    def set_default_moderation_state
      self.moderation_state ||= user_detail.moderation_state
    end
  end
end

app/models/concerns/thredded/friendly_id_reserved_words_and_pagination.rb
# frozen_string_literal: true

require 'set'
module Thredded
  # Excludes pagination routes in addition to the given list of reserved words.
  class FriendlyIdReservedWordsAndPagination
    PAGINATION_PATTERN = /\Apage-\d+\z/i

    def initialize(words = [])
      @words = Set.new(words)
    end

    def include?(slug)
      @words.include?(slug) || slug =~ PAGINATION_PATTERN
    end
  end
end

app/models/concerns/thredded/moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Defines a moderation_state enum
  # Requires an integer moderation_state column on the including class.
  module ModerationState
    extend ActiveSupport::Concern

    included do
      enum moderation_state: %i[pending_moderation approved blocked]
      validates :moderation_state, presence: true
    end
  end
end

app/models/concerns/thredded/notifier_preference.rb
# frozen_string_literal: true

module Thredded
  module NotifierPreference
    extend ActiveSupport::Concern

    included do
      delegate :human_name, to: :notifier, prefix: true

      def self.detect_or_default(prefs, notifier)
        (prefs && prefs.find { |pref| pref.notifier_key == notifier.key }) || default(notifier)
      end
    end

    def notifier
      @notifier ||= Thredded.notifiers.find { |notifier| notifier.key == notifier_key }
    end
  end
end

app/models/concerns/thredded/post_common.rb
# frozen_string_literal: true

module Thredded
  # @abstract Classes that include this module are expected to implement {#readers}.
  # @!method readers
  #     @abstract
  #     @return [ActiveRecord::Relation<Thredded.user_class>] users from that can read this post.
  module PostCommon
    extend ActiveSupport::Concern

    included do
      paginates_per 50

      delegate :email, to: :user, prefix: true, allow_nil: true

      validates :content, presence: true

      scope :order_oldest_first, -> { order(created_at: :asc, id: :asc) }
      scope :order_newest_first, -> { order(created_at: :desc, id: :desc) }

      before_validation :ensure_user_detail, on: :create
    end

    def avatar_url
      Thredded.avatar_url.call(user)
    end

    def calculate_page(postable_posts, per_page)
      1 + postable_posts.where(postable_posts.arel_table[:created_at].lt(created_at)).count / per_page
    end

    # @param view_context [Object] the context of the rendering view.
    # @return [String] formatted and sanitized html-safe post content.
    def filtered_content(view_context, users_provider: ->(names) { readers_from_user_names(names) }, **options)
      Thredded::ContentFormatter.new(view_context, users_provider: users_provider, **options).format_content(content)
    end

    def first_post_in_topic?
      postable.first_post == self
    end

    # @return [ActiveRecord::Relation<Thredded.user_class>] users from the list of user names that can read this post.
    # @api private
    def readers_from_user_names(user_names)
      DbTextSearch::CaseInsensitive
        .new(readers, Thredded.user_name_column)
        .in(user_names)
    end

    # Marks all the posts from the given one as unread for the given user
    # @param user [Thredded.user_class]
    # @param page [Integer]
    def mark_as_unread(user, page)
      if previous_post.nil?
        read_state = postable.user_read_states.find_by(user_id: user.id)
        read_state.destroy if read_state
      else
        read_state = postable.user_read_states.create_with(
          read_at: previous_post.created_at,
          page: page
        ).find_or_create_by(user_id: user.id)
        read_state.update_columns(read_at: previous_post.created_at, page: page)
      end
    end

    def previous_post
      @previous_post ||= postable.posts.order_newest_first.find_by('created_at < ?', created_at)
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end
  end
end

app/models/concerns/thredded/search_parser.rb
# frozen_string_literal: true

module Thredded
  class SearchParser
    def initialize(query)
      @query = query
      @keywords = %w[in by order]
    end

    def parse
      parsed_input = parse_keywords
      parsed_input['text'] = parse_text
      parsed_input
    end

    def parse_keywords
      found_terms_hash = {}

      @keywords.each do |keyword|
        regex = Regexp.new(keyword + '\s*:\s*\w+', Regexp::IGNORECASE)
        keyword_scan = @query.scan(regex)
        @query = @query.gsub(regex, '')

        next if keyword_scan.blank?
        keyword_scan.each do |term|
          found_terms_hash[keyword] ||= []
          found_terms_hash[keyword] << term.delete(' ').split(':')[1]
        end
      end

      found_terms_hash
    end

    def parse_text
      regex = Regexp.new('\"[^"]*\"')
      found_terms = @query.scan(regex)
      @query = @query.sub(regex, '')
      found_terms.concat(@query.split(/\s+/))
    end
  end
end

app/models/concerns/thredded/topics_search.rb
# frozen_string_literal: true

module Thredded
  class TopicsSearch
    def initialize(query, scope)
      @terms = Thredded::SearchParser.new(query).parse
      @scope = scope

      @search_categories = @search_users = @search_text = nil
    end

    # @return [ActiveRecord::Relation<Thredded::Topic>]
    def search
      if categories.present?
        @scope = @scope.joins(:topic_categories).merge(Thredded::TopicCategory.where(category_id: categories))
      end
      if text.present? || users.present?
        [search_topics, search_posts].compact.reduce(:union)
      else
        @scope
      end
    end

    protected

    def search_topics
      scope = @scope
      scope = @scope.where(user_id: users) if users.present?
      scope = DbTextSearch::FullText.new(scope, :title).search(text) if text.present?
      scope
    end

    def search_posts
      posts_scope = Thredded::Post
      posts_scope = posts_scope.where(user_id: users) if users.present?
      posts_scope = DbTextSearch::FullText.new(posts_scope, :content).search(text) if text.present?
      @scope.joins(:posts).merge(posts_scope)
    end

    def categories
      @search_categories ||=
        if @terms['in'].present?
          DbTextSearch::CaseInsensitive
            .new(Category, :name)
            .in(@terms['in']).pluck(:id)
        else
          []
        end
    end

    def users
      @search_users ||=
        if @terms['by']
          DbTextSearch::CaseInsensitive
            .new(Thredded.user_class, Thredded.user_name_column)
            .in(@terms['by']).pluck(:id)
        else
          []
        end
    end

    # @return [Array<String>]
    def text
      @terms['text']
    end
  end
end

app/models/thredded/category.rb
# frozen_string_literal: true

module Thredded
  class Category < ActiveRecord::Base
    extend FriendlyId
    belongs_to :messageboard
    has_many :topic_categories
    has_many :topics, through: :topic_categories
    friendly_id :name, use: %i[history scoped], scope: :messageboard

    validates :name, presence: true
    validates :messageboard_id, presence: true

    def normalize_friendly_id(input)
      Thredded.slugifier.call(input.to_s)
    end
  end
end

app/models/thredded/messageboard.rb
# frozen_string_literal: true

module Thredded
  class Messageboard < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates,
                use:            %i[slugged reserved],
                # Avoid route conflicts
                reserved_words: ::Thredded::FriendlyIdReservedWordsAndPagination.new(
                  %w[
                    admin
                    autocomplete-users
                    messageboards
                    posts
                    preferences
                    private-posts
                    private-topics
                    theme-preview
                  ]
                )

    validates :name, uniqueness: true, length: { maximum: 60 }, presence: true
    validates :topics_count, numericality: true
    validates :position, presence: true, on: :update
    before_save :ensure_position, on: :create

    def ensure_position
      self.position ||= (created_at || Time.zone.now).to_i
    end

    has_many :categories, dependent: :destroy
    has_many :user_messageboard_preferences, dependent: :destroy
    has_many :posts, dependent: :destroy
    has_many :topics, dependent: :destroy, inverse_of: :messageboard

    belongs_to :last_topic, class_name: 'Thredded::Topic', **(Thredded.rails_gte_51? ? { optional: true } : {})

    has_many :user_details, through: :posts
    has_many :messageboard_users,
             inverse_of:  :messageboard,
             foreign_key: :thredded_messageboard_id,
             dependent: :destroy
    has_many :recently_active_user_details,
             -> { merge(Thredded::MessageboardUser.recently_active) },
             class_name: 'Thredded::UserDetail',
             through:    :messageboard_users,
             source:     :user_detail
    has_many :recently_active_users,
             class_name: Thredded.user_class_name,
             through:    :recently_active_user_details,
             source:     :user

    belongs_to :group,
               inverse_of: :messageboards,
               foreign_key: :messageboard_group_id,
               class_name: 'Thredded::MessageboardGroup',
               **(Thredded.rails_gte_51? ? { optional: true } : {})

    has_many :post_moderation_records, inverse_of: :messageboard, dependent: :delete_all

    # rubocop:disable Style/Lambda
    scope :top_level_messageboards, -> { where(group: nil) }
    scope :by_messageboard_group, ->(group) { where(group: group.id) }
    scope :ordered, ->(order = Thredded.messageboards_order) {
      case order
      when :position
        self
      when :created_at_asc
        ordered_by_created_at_asc
      when :last_post_at_desc
        ordered_by_last_post_at_desc
      when :topics_count_desc
        ordered_by_topics_count_desc
      end.ordered_by_position.order(id: :asc)
    }
    scope :ordered_by_position, ->() { order(position: :asc) }
    scope :ordered_by_created_at_asc, ->() { order(created_at: :asc) }
    scope :ordered_by_last_post_at_desc, ->() {
      joins('LEFT JOIN thredded_topics AS last_topics ON thredded_messageboards.last_topic_id = last_topics.id')
        .order('COALESCE(last_topics.last_post_at, thredded_messageboards.created_at) DESC')
    }
    scope :ordered_by_topics_count_desc, ->() {
      order(topics_count: :desc)
    }
    # rubocop:enable Style/Lambda

    # Finds the messageboard by its slug or ID, or raises Thredded::Errors::MessageboardNotFound.
    # @param slug_or_id [String]
    # @return [Thredded::Messageboard]
    # @raise [Thredded::Errors::MessageboardNotFound] if the messageboard with the given slug does not exist.
    def self.friendly_find!(slug_or_id)
      friendly.find(slug_or_id)
    rescue ActiveRecord::RecordNotFound
      raise Thredded::Errors::MessageboardNotFound
    end

    def last_user
      last_topic.try(:last_user)
    end

    def update_last_topic!
      return if destroyed?
      self.last_topic = topics.order_recently_posted_first.moderation_state_visible_to_all.first
      save! if last_topic_id_changed?
    end

    def normalize_friendly_id(input)
      Thredded.slugifier.call(input.to_s)
    end

    private

    def slug_candidates
      [
        :name,
        [:name, '-board']
      ]
    end
  end
end

app/models/thredded/messageboard_group.rb
# frozen_string_literal: true

module Thredded
  class MessageboardGroup < ActiveRecord::Base
    has_many :messageboards,
             inverse_of: :group,
             foreign_key: :messageboard_group_id,
             dependent: :nullify

    scope :ordered, -> { order(position: :asc, id: :asc) }
    validates :name, presence: true, uniqueness: true
    validates :position, presence: true, on: :update
    before_save :ensure_position, on: :create

    def ensure_position
      self.position ||= Time.zone.now.to_i
    end
  end
end

app/views/thredded/topics/_followers.html.erb
<% if Thredded.show_topic_followers %>
  <div class="thredded--topic-followers">
    <% if topic.followers.present? %>
      <%= t('thredded.topics.followed_by')%>
      <% topic.followers.each do |user| %>
        <%= user_mention(user) %>
      <% end %>
    <% else %>
      <%= t('thredded.topics.followed_by_noone')%>
    <% end %>
  </div>
<% end %>

app/views/thredded/topics/_form.html.erb
<%= form_for topic,
             url: topic.submit_path,
             html: {
                 class: "thredded--form thredded--new-topic-form #{local_assigns[:css_class]}",
                 'data-thredded-topic-form' => true,
                 'data-autocomplete-url' => autocomplete_users_path,
                 'data-autocomplete-min-length' => Thredded.autocomplete_min_length,
             } do |form| %>
  <ul class="thredded--form-list on-top">
    <li class="title">
      <%= form.label :title, t('thredded.topics.form.title_label') %>
      <%= form.text_field :title, placeholder: placeholder, required: true %>
    </li>

    <% if form.object.category_options.any? %>
      <li class="category">
        <%= form.select :category_ids,
                        form.object.category_options,
                        {},
                        { multiple: true, 'data-placeholder' => t('thredded.topics.form.categories_placeholder') } %>
      </li>
    <% end %>

    <%= render 'thredded/posts_common/form/content',
               form: form,
               content_label: t('thredded.topics.form.content_label'),
               preview_url: topic.preview_path %>
    <%= render 'thredded/topics/topic_form_admin_options', form: form %>

    <li><%= form.submit t('thredded.topics.form.create_btn'), class: 'thredded--form--submit' %></li>
  </ul>
<% end %>

app/views/thredded/topics/_header.html.erb
<header class="thredded--topic-header">
  <h1 class="thredded--topic-header--title"><%= topic.title %></h1>
  <cite class="thredded--topic-header--started-by">
    <%= t 'thredded.topics.started_by_html',
          time_ago: time_ago(topic.created_at),
          user:     user_link(topic.user) %>
  </cite>
  <% if topic.can_update? %>
    <%= link_to t('thredded.topics.edit'), topic.edit_path,
                class: 'thredded--topic-header--edit-topic',
                rel: 'nofollow' %>
  <% end %>
  <% if thredded_current_user %>
    <% if topic.followed? %>
      <div class="thredded--topic-header--follow-info">
        <span class="thredded--topic-header--follow-info--reason">
          <%= topic_follow_reason_text topic.follow_reason %>
        </span>
        <%= button_to topic.unfollow_path, form: {class: 'thredded--topic-header--follow-info--unfollow'} do %>
          <%= t('thredded.topics.unfollow') %>
          <%= inline_svg 'thredded/follow.svg', class: 'thredded--topic-header--follow-icon' %>
        <% end %>
      </div>
    <% else %>
      <div class="thredded--topic-header--follow-info">
        <%= button_to t('thredded.topics.follow'), topic.follow_path,
                      form: {class: 'thredded--topic-header--follow-info--follow'} %>
      </div>
    <% end %>
  <% end %>
  <%= render partial: 'thredded/topics/followers', locals: {topic: topic} %>
</header>

app/views/thredded/topics/_sticky_topics_divider.html.erb
<hr class="thredded--topics--sticky-topics-divider">

app/views/thredded/topics/_topic.html.erb
<%= content_tag :article,
                id:    dom_id(topic),
                class: ['thredded--topics--topic', topic_css_classes(topic)],
                data: {topic: topic.id, messageboard: topic.messageboard_id} do %>
  <div class="thredded--topics--posts-count"><%= topic.posts_count %></div>

  <div class="thredded--topics--follow-info" title="<%= topic_follow_reason_text topic.follow_reason %>">
    <svg class="thredded--topics--follow-icon" viewBox="0 0 116 121" role="img">
      <% if topic.followed? %>
        <use xlink:href="#thredded-follow-icon"></use>
      <% else %>
        <use xlink:href="#thredded-unfollow-icon"></use>
      <% end %>
    </svg>
  </div>

  <h1 class="thredded--topics--title">
    <%= link_to topic.title, topic.path %>
  </h1>

  <% if topic.categories.any? %>
    <ul class="thredded--topics--categories">
      <%= render topic.categories %>
    </ul>
  <% end %>

  <cite class="thredded--topics--updated-by">
    <%= time_ago topic.last_post_at %>
    <%= user_link topic.last_user %>
  </cite>

  <cite class="thredded--topics--started-by">
    <%= time_ago topic.created_at %>
    <%= user_link topic.user %>
  </cite>

  <% if topic.blocked? && topic.can_moderate? %>
    <span class="thredded--topics--moderation-state thredded--alert thredded--alert-danger">
      <%= render 'thredded/shared/content_moderation_blocked_state', moderation_record: topic.last_moderation_record %>
    </span>
  <% end %>
<% end %>

<% if local_assigns[:sticky_topics_divider] &&
    !topic_iteration.last? && topic.sticky? && !topics[topic_counter + 1].sticky? %>
  <%= render 'thredded/topics/sticky_topics_divider' %>
<% end %>

app/views/thredded/topics/_topic_form_admin_options.html.erb
<% topic = form.object.respond_to?(:topic) ? form.object.topic : form.object %>
<% if policy(topic).moderate? %>
  <li class="thredded--form-list--admin-options">
    <%= form.label :locked do %>
      <%= form.check_box :locked %> <%= t 'thredded.topics.locked.label' %>
    <% end %>

    <%= form.label :sticky do %>
      <%= form.check_box :sticky %> <%= t 'thredded.topics.sticky.label' %>
    <% end %>
  </li>
<% end %>

app/views/thredded/topics/edit.html.erb
<% content_for :thredded_page_title, t('thredded.nav.edit_topic') %>
<% content_for :thredded_page_id, 'thredded--edit-topic' %>
<% content_for :thredded_breadcrumbs do %>
  <ul class="thredded--navigation-breadcrumbs">
    <li><%= link_to t('thredded.nav.all_messageboards'), messageboards_path %></li>
    <li><%= link_to messageboard.name, @edit_topic.messageboard_path %></li>
    <li><%= link_to @edit_topic.title, @edit_topic.path %></li>
    <li><%= link_to t('thredded.nav.edit_topic'), @edit_topic.edit_path %></li>
  </ul>
<% end %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= form_for @edit_topic,
                 url: @edit_topic.path,
                 html: { class: 'thredded--form thredded--is-expanded', 'data-thredded-topic-form' => true } do |form| %>
      <ul class="thredded--form-list on-top">

        <li class="title">
          <%= form.label :title, t('thredded.topics.form.title_label') %>
          <%= form.text_field :title,
                              placeholder: t('thredded.topics.form.title_placeholder'),
                              autofocus: true,
                              required: true %>
        </li>

        <% if form.object.category_options.any? %>
          <li class="category">
            <%= form.select :category_ids, form.object.category_options, {},
                            multiple: true,
                            'data-placeholder' => t('thredded.topics.form.categories_placeholder') %>
          </li>
        <% end %>

        <li>
          <%= form.label :messageboard_id, t('thredded.topics.form.messageboard_label') %>
          <%= form.select :messageboard_id, form.object.messageboard_options %>
        </li>

        <%= render 'thredded/topics/topic_form_admin_options', form: form %>

        <li>
          <button type="submit" class="thredded--form--submit">
            <%= t('thredded.topics.form.update_btn') %>
          </button>
        </li>
    <% end %>
    </ul>
  </section>
<% end %>

app/views/thredded/topics/index.html.erb
<% content_for :thredded_page_title, messageboard.name %>
<% content_for :thredded_page_id, 'thredded--topics-index' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>

<%= thredded_page do %>
  <div class="thredded--svg-definitions ">
    <%= inline_svg 'thredded/follow.svg', id: 'thredded-follow-icon', title: nil %>
    <%= inline_svg 'thredded/unfollow.svg', id: 'thredded-unfollow-icon' %>
  </div>

  <%= content_tag :section, class: 'thredded--main-section thredded--topics', 'data-thredded-topics' => true do %>
    <%= render 'thredded/topics/form',
               topic: @new_topic,
               css_class: 'thredded--is-compact',
               placeholder: t('thredded.topics.form.title_placeholder_start') if @new_topic %>
    <%= render partial: 'thredded/topics/topic',
               collection: @topics,
               locals: {
                 sticky_topics_divider: true,
                 topics: @topics
               } %>
  <% end %>

  <footer class="thredded--pagination-bottom">
    <%= paginate @topics %>
  </footer>

  <div class="thredded--messageboards--actions">
    <% if policy(messageboard).update? %>
      <a class="thredded--button" href="<%= edit_messageboard_path(messageboard) %>" rel="nofollow">
        <%= t('thredded.nav.edit_messageboard') %>
      </a>
    <% end %>
  </div>
<% end %>

app/views/thredded/topics/new.html.erb
<% content_for :thredded_page_title, t('thredded.topics.create') %>
<% content_for :thredded_page_id, 'thredded--new-topic' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= render 'thredded/topics/form',
               topic: @new_topic,
               css_class: 'thredded--is-expanded',
               placeholder: t('thredded.topics.form.title_placeholder_start') %>
  </section>
<% end %>

app/views/thredded/topics/search.html.erb
<% content_for :thredded_page_title, t('thredded.topics.search.page_title') %>
<% content_for :thredded_page_id, 'thredded--topic-search-results' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>

<%= thredded_page do %>
  <% if @topics.present? %>
    <p class="thredded--alert thredded--alert-success">
      <% if messageboard_or_nil %>
        <%= t 'thredded.topics.search.results_in_messageboard_message_html',
              query: @query, messageboard: messageboard.name %>
        <br>
        <a href="<%= messageboards_search_path(q: @query) %>">
          <%= t('thredded.topics.search.search_in_all_messageboards_btn') -%>
        </a>
      <% else %>
        <%= t 'thredded.topics.search.results_message_html', query: @query %>
      <% end %>
    </p>
    <section class="thredded--main-section thredded--topics">
      <%= render @topics %>
    </section>
    <footer class="thredded--pagination-bottom">
      <%= paginate @topics %>
    </footer>
  <% else %>
    <p class="thredded--alert thredded--alert-danger">
      <% if messageboard_or_nil %>
        <%= t 'thredded.topics.search.no_results_in_messageboard_message_html',
              query: @query, messageboard: messageboard.name -%>
        <br>
        <a href="<%= messageboards_search_path(q: @query) %>">
          <%= t('thredded.topics.search.search_in_all_messageboards_btn') -%>
        </a>
      <% else %>
        <%= t 'thredded.topics.search.no_results_message_html', query: @query %>
      <% end %>
    </p>
  <% end %>
<% end %>