config/routes.rb
# frozen_string_literal: true

Thredded::Engine.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :theme_preview, only: [:show], path: 'theme-preview' if %w[development test].include? Rails.env

  page_constraint = { page: /[1-9]\d*/ }

  scope path: 'private-topics' do
    resource :read_state, only: [:update], as: :mark_all_private_topics_read
    resource :private_topic, only: [:new], path: '' do
      post :preview, on: :new, controller: 'private_topic_previews'
    end
    resources :private_topics, except: %i[new show], path: '' do
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint
      end
      resources :private_posts, path: '', except: %i[index show] do
        post :preview, on: :new, controller: 'private_post_previews'
        resource :preview, only: [:update], controller: 'private_post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  scope only: [:show], constraints: { id: Thredded.routes_id_constraint } do
    resources :private_post_permalinks, path: 'private-posts'
    resources :post_permalinks, path: 'posts'
  end

  resources :autocomplete_users, only: [:index], path: 'autocomplete-users'

  constraints(->(req) { req.env['QUERY_STRING'].include? 'q=' }) do
    get '/' => 'topics#search', as: :messageboards_search
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  scope path: 'admin' do
    resources :messageboard_groups, only: %i[new create]
    scope controller: :moderation, path: 'moderation' do
      scope constraints: page_constraint do
        get '(/page-:page)', action: :pending, as: :pending_moderation
        get '/history(/page-:page)', action: :history, as: :moderation_history
        get '/users(/page-:page)', action: :users, as: :users_moderation
        get '/users/:id(/page-:page)', action: :user, as: :user_moderation
        get '/activity(/page-:page)', action: :activity, as: :moderation_activity
      end
      post '', action: :moderate_post, as: :moderate_post
      post '/user/:id', action: :moderate_user, as: :moderate_user
    end
  end

  resource :preferences, only: %i[edit update], as: :global_preferences
  resource :messageboard, path: 'messageboards', only: [:new]
  resources :messageboards, only: %i[edit update]
  resources :messageboards, only: %i[index create], path: '' do
    resource :preferences, only: %i[edit update]
    resource :topic, path: 'topics', only: [:new] do
      post :preview, on: :new, controller: 'topic_previews'
    end
    resources :topics, path: '', except: %i[index new show] do
      collection do
        get '(page-:page)', action: :index, as: '', constraints: page_constraint
        get '/category/:category_id', action: :category, as: :categories
      end
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint

        # match (un)follow via get as well so that redirecting back to it after sign in works.
        match 'follow', via: %i[post get]
        match 'unfollow', via: %i[post get]
      end
      resources :posts, except: %i[index show], path: '' do
        post :preview, on: :new, controller: 'post_previews'
        resource :preview, only: [:update], controller: 'post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  root to: 'messageboards#index'
end

app/models/concerns/thredded/content_moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Moderation state of a piece of content, such as a Thredded::Topic or a Thredded::Post.
  # Requires an integer moderation_state column, a user_id column, and a user_detail association on the including class.
  # @api private
  module ContentModerationState
    extend ActiveSupport::Concern
    include Thredded::ModerationState

    included do
      before_validation :set_default_moderation_state, on: :create

      scope :moderation_state_visible_to_all, -> { where(visible_to_all_arel_node) }

      scope :moderation_state_visible_to_user, (lambda do |user|
        visible = visible_to_all_arel_node
        # @type [Arel::Table]
        table = arel_table
        if user && !user.thredded_anonymous?
          # Own content
          visible = visible.or(table[:user_id].eq(user.id))
          # Content that one can moderate
          moderatable_messageboard_ids = user.thredded_can_moderate_messageboards.map(&:id)
          if moderatable_messageboard_ids.present?
            visible = visible.or(table[:messageboard_id].in(moderatable_messageboard_ids))
          end
        end
        where(visible)
      end)

      # @return [Arel::Nodes::Node]
      # @api private
      def self.visible_to_all_arel_node
        if Thredded.content_visible_while_pending_moderation
          # All non-blocked content
          arel_table[:moderation_state].not_eq(moderation_states[:blocked])
        else
          # Only approved content
          arel_table[:moderation_state].eq(moderation_states[:approved])
        end
      end
    end

    # Whether this is visible to anyone based on the moderation state.
    def moderation_state_visible_to_all?
      if Thredded.content_visible_while_pending_moderation
        !blocked?
      else
        approved?
      end
    end

    # Whether this is visible to the given user based on the moderation state.
    def moderation_state_visible_to_user?(user)
      moderation_state_visible_to_all? ||
        (!user.thredded_anonymous? &&
          (user_id == user.id || user.thredded_can_moderate_messageboards.map(&:id).include?(messageboard_id)))
    end

    private

    def set_default_moderation_state
      self.moderation_state ||= user_detail.moderation_state
    end
  end
end

app/models/concerns/thredded/friendly_id_reserved_words_and_pagination.rb
# frozen_string_literal: true

require 'set'
module Thredded
  # Excludes pagination routes in addition to the given list of reserved words.
  class FriendlyIdReservedWordsAndPagination
    PAGINATION_PATTERN = /\Apage-\d+\z/i

    def initialize(words = [])
      @words = Set.new(words)
    end

    def include?(slug)
      @words.include?(slug) || slug =~ PAGINATION_PATTERN
    end
  end
end

app/models/concerns/thredded/moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Defines a moderation_state enum
  # Requires an integer moderation_state column on the including class.
  module ModerationState
    extend ActiveSupport::Concern

    included do
      enum moderation_state: %i[pending_moderation approved blocked]
      validates :moderation_state, presence: true
    end
  end
end

app/models/concerns/thredded/notifier_preference.rb
# frozen_string_literal: true

module Thredded
  module NotifierPreference
    extend ActiveSupport::Concern

    included do
      delegate :human_name, to: :notifier, prefix: true

      def self.detect_or_default(prefs, notifier)
        (prefs && prefs.find { |pref| pref.notifier_key == notifier.key }) || default(notifier)
      end
    end

    def notifier
      @notifier ||= Thredded.notifiers.find { |notifier| notifier.key == notifier_key }
    end
  end
end

app/models/concerns/thredded/post_common.rb
# frozen_string_literal: true

module Thredded
  # @abstract Classes that include this module are expected to implement {#readers}.
  # @!method readers
  #     @abstract
  #     @return [ActiveRecord::Relation<Thredded.user_class>] users from that can read this post.
  module PostCommon
    extend ActiveSupport::Concern

    included do
      paginates_per 50

      delegate :email, to: :user, prefix: true, allow_nil: true

      validates :content, presence: true

      scope :order_oldest_first, -> { order(created_at: :asc, id: :asc) }
      scope :order_newest_first, -> { order(created_at: :desc, id: :desc) }

      before_validation :ensure_user_detail, on: :create
    end

    def avatar_url
      Thredded.avatar_url.call(user)
    end

    def calculate_page(postable_posts, per_page)
      1 + postable_posts.where(postable_posts.arel_table[:created_at].lt(created_at)).count / per_page
    end

    # @param view_context [Object] the context of the rendering view.
    # @return [String] formatted and sanitized html-safe post content.
    def filtered_content(view_context, users_provider: ->(names) { readers_from_user_names(names) }, **options)
      Thredded::ContentFormatter.new(view_context, users_provider: users_provider, **options).format_content(content)
    end

    def first_post_in_topic?
      postable.first_post == self
    end

    # @return [ActiveRecord::Relation<Thredded.user_class>] users from the list of user names that can read this post.
    # @api private
    def readers_from_user_names(user_names)
      DbTextSearch::CaseInsensitive
        .new(readers, Thredded.user_name_column)
        .in(user_names)
    end

    # Marks all the posts from the given one as unread for the given user
    # @param user [Thredded.user_class]
    # @param page [Integer]
    def mark_as_unread(user, page)
      if previous_post.nil?
        read_state = postable.user_read_states.find_by(user_id: user.id)
        read_state.destroy if read_state
      else
        read_state = postable.user_read_states.create_with(
          read_at: previous_post.created_at,
          page: page
        ).find_or_create_by(user_id: user.id)
        read_state.update_columns(read_at: previous_post.created_at, page: page)
      end
    end

    def previous_post
      @previous_post ||= postable.posts.order_newest_first.find_by('created_at < ?', created_at)
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end
  end
end

app/models/concerns/thredded/search_parser.rb
# frozen_string_literal: true

module Thredded
  class SearchParser
    def initialize(query)
      @query = query
      @keywords = %w[in by order]
    end

    def parse
      parsed_input = parse_keywords
      parsed_input['text'] = parse_text
      parsed_input
    end

    def parse_keywords
      found_terms_hash = {}

      @keywords.each do |keyword|
        regex = Regexp.new(keyword + '\s*:\s*\w+', Regexp::IGNORECASE)
        keyword_scan = @query.scan(regex)
        @query = @query.gsub(regex, '')

        next if keyword_scan.blank?
        keyword_scan.each do |term|
          found_terms_hash[keyword] ||= []
          found_terms_hash[keyword] << term.delete(' ').split(':')[1]
        end
      end

      found_terms_hash
    end

    def parse_text
      regex = Regexp.new('\"[^"]*\"')
      found_terms = @query.scan(regex)
      @query = @query.sub(regex, '')
      found_terms.concat(@query.split(/\s+/))
    end
  end
end

app/models/concerns/thredded/topic_common.rb
# frozen_string_literal: true

module Thredded
  module TopicCommon
    extend ActiveSupport::Concern
    included do
      paginates_per 50 if respond_to?(:paginates_per)

      belongs_to :last_user,
                 class_name: Thredded.user_class_name,
                 foreign_key: 'last_user_id',
                 **(Thredded.rails_gte_51? ? { optional: true } : {})

      scope :order_recently_posted_first, -> { order(last_post_at: :desc, id: :desc) }
      scope :on_page, ->(page_num) { page(page_num) }

      validates :hash_id, presence: true, uniqueness: true
      validates :posts_count, numericality: true

      before_validation do
        self.hash_id = SecureRandom.hex(10) if hash_id.nil?
      end

      delegate :name, :name=, :email, :email=, to: :user, prefix: true

      before_validation :ensure_user_detail, on: :create
    end

    def user
      super || Thredded::NullUser.new
    end

    def last_user
      super || Thredded::NullUser.new
    end

    def private?
      !public?
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end

    module ClassMethods
      # @param user [Thredded.user_class]
      # @return [ActiveRecord::Relation]
      def unread(user)
        topics      = arel_table
        reads_class = reflect_on_association(:user_read_states).klass
        reads       = reads_class.arel_table
        joins(topics.join(reads, Arel::Nodes::OuterJoin)
                .on(topics[:id].eq(reads[:postable_id]).and(reads[:user_id].eq(user.id))).join_sources)
          .merge(reads_class.where(reads[:id].eq(nil).or(reads[:read_at].lt(topics[:last_post_at]))))
      end

      private

      # @param user [Thredded.user_class]
      # @return [ByPostableLookup]
      def read_states_by_postable_hash(user)
        read_states = reflect_on_association(:user_read_states).klass
          .where(user_id: user.id, postable_id: current_scope.map(&:id))
        Thredded::TopicCommon::CachingHash.from_relation(read_states)
      end

      public

      # @param user [Thredded.user_class]
      # @return [Array<[TopicCommon, UserTopicReadStateCommon]>]
      def with_read_states(user)
        null_read_state = Thredded::NullUserTopicReadState.new
        return current_scope.zip([null_read_state]) if user.thredded_anonymous?
        read_states_by_postable = read_states_by_postable_hash(user)
        current_scope.map do |postable|
          [postable, read_states_by_postable[postable] || null_read_state]
        end
      end
    end

    class CachingHash < Hash
      def self.from_relation(postable_relation)
        self[postable_relation.map { |related| [related.postable_id, related] }]
      end

      # lookup related item by postable and set the inverse lookup
      def [](postable)
        super(postable.id).tap { |related| related.postable = postable if related }
      end
    end
  end
end

app/models/concerns/thredded/topics_search.rb
# frozen_string_literal: true

module Thredded
  class TopicsSearch
    def initialize(query, scope)
      @terms = Thredded::SearchParser.new(query).parse
      @scope = scope

      @search_categories = @search_users = @search_text = nil
    end

    # @return [ActiveRecord::Relation<Thredded::Topic>]
    def search
      if categories.present?
        @scope = @scope.joins(:topic_categories).merge(Thredded::TopicCategory.where(category_id: categories))
      end
      if text.present? || users.present?
        [search_topics, search_posts].compact.reduce(:union)
      else
        @scope
      end
    end

    protected

    def search_topics
      scope = @scope
      scope = @scope.where(user_id: users) if users.present?
      scope = DbTextSearch::FullText.new(scope, :title).search(text) if text.present?
      scope
    end

    def search_posts
      posts_scope = Thredded::Post
      posts_scope = posts_scope.where(user_id: users) if users.present?
      posts_scope = DbTextSearch::FullText.new(posts_scope, :content).search(text) if text.present?
      @scope.joins(:posts).merge(posts_scope)
    end

    def categories
      @search_categories ||=
        if @terms['in'].present?
          DbTextSearch::CaseInsensitive
            .new(Category, :name)
            .in(@terms['in']).pluck(:id)
        else
          []
        end
    end

    def users
      @search_users ||=
        if @terms['by']
          DbTextSearch::CaseInsensitive
            .new(Thredded.user_class, Thredded.user_name_column)
            .in(@terms['by']).pluck(:id)
        else
          []
        end
    end

    # @return [Array<String>]
    def text
      @terms['text']
    end
  end
end

app/models/concerns/thredded/user_topic_read_state_common.rb
# frozen_string_literal: true

module Thredded
  module UserTopicReadStateCommon
    extend ActiveSupport::Concern
    included do
      extend ClassMethods
      validates :user_id, uniqueness: { scope: :postable_id }
    end

    # @return [Boolean]
    def read?
      postable.last_post_at <= read_at
    end

    # @param post [Post or PrivatePost]
    # @return [Boolean]
    def post_read?(post)
      post.created_at <= read_at
    end

    module ClassMethods
      # @param user_id [Integer]
      # @param topic_id [Integer]
      # @param post [Thredded::PostCommon]
      # @param post_page [Integer]
      def touch!(user_id, topic_id, post, post_page)
        # TODO: Switch to upsert once Travis supports PostgreSQL 9.5.
        # Travis issue: https://github.com/travis-ci/travis-ci/issues/4264
        # Upsert gem: https://github.com/seamusabshere/upsert
        state = find_or_initialize_by(user_id: user_id, postable_id: topic_id)
        fail ArgumentError, "expected post_page >= 1, given #{post_page.inspect}" if post_page < 1
        return unless !state.read_at? || state.read_at < post.created_at
        state.update!(read_at: post.created_at, page: post_page)
      end

      def read_on_first_post!(user, topic)
        create!(user: user, postable: topic, read_at: Time.zone.now, page: 1)
      end
    end
  end
end

app/models/thredded/category.rb
# frozen_string_literal: true

module Thredded
  class Category < ActiveRecord::Base
    extend FriendlyId
    belongs_to :messageboard
    has_many :topic_categories
    has_many :topics, through: :topic_categories
    friendly_id :name, use: %i[history scoped], scope: :messageboard

    validates :name, presence: true
    validates :messageboard_id, presence: true

    def normalize_friendly_id(input)
      Thredded.slugifier.call(input.to_s)
    end
  end
end

app/models/thredded/null_user_topic_read_state.rb
# frozen_string_literal: true

module Thredded
  class NullUserTopicReadState
    def page
      1
    end

    def read?
      false
    end

    def post_read?(_post)
      false
    end
  end
end

app/views/thredded/moderation/_nav.html.erb
<% content_for :thredded_main_navigation do %>
  <nav class="thredded--moderation-navigation">
    <ul class="thredded--moderation-navigation--items">
      <li class="thredded--moderation-navigation--item thredded--moderation-navigation--pending">
        <%= link_to t('thredded.nav.moderation_pending'), pending_moderation_path %>
      </li>
      <li class="thredded--moderation-navigation--item thredded--moderation-navigation--history">
        <%= link_to t('thredded.nav.moderation_history'), moderation_history_path %>
      </li>
      <li class="thredded--moderation-navigation--item thredded--moderation-navigation--activity">
        <%= link_to t('thredded.nav.moderation_activity'), moderation_activity_path %>
      </li>
      <li class="thredded--moderation-navigation--item thredded--moderation-navigation--users">
        <%= link_to t('thredded.nav.moderation_users'), users_moderation_path %>
      </li>
    </ul>
    <%= render 'users_search_form' %>
  </nav>
<% end %>

app/views/thredded/moderation/_post.html.erb
<% post, content = post_and_content if local_assigns.key?(:post_and_content) %>
<%= content_tag :article, id: dom_id(post), class: 'thredded--post thredded--post-moderation' do %>
  <%= render 'thredded/posts_common/actions', post: post %>
  <%= render 'thredded/posts_common/header_with_user_and_topic',
             post:           post,
             post_user_link: if post.user
                               link_to(post.user.thredded_display_name, user_moderation_path(post.user.id))
                             else
                               content_tag :em, t('thredded.null_user_name')
                             end
  %>
  <%= content || render('thredded/posts/content', post: post) %>
  <% if post.blocked? %>
    <p class="thredded--alert thredded--alert-danger">
      <%= render 'thredded/shared/content_moderation_blocked_state', moderation_record: post.last_moderation_record %>
    </p>
  <% end %>
  <%= render 'post_moderation_actions', post: post %>
<% end %>

app/views/thredded/moderation/_post_moderation_actions.html.erb
<div class="thredded--post-moderation-actions">
  <% unless post.approved? %>
    <%= button_to t('thredded.moderation.approve_btn'), moderate_post_path,
                  class:  'thredded--button',
                  params: { id: post.to_model.id, moderation_state: 'approved' } %>
  <% end %>
  <% unless post.blocked? %>
    <%= button_to t('thredded.moderation.block_btn'), moderate_post_path,
                  class:  'thredded--button',
                  params: { id: post.to_model.id, moderation_state: 'blocked' } %>
  <% end %>
</div>

app/views/thredded/moderation/_post_moderation_record.html.erb
<%
  record = post_moderation_record
  post = record.post
  if post
    post_view = Thredded::PostView.new(post, policy(post))
  end
  moderation_state_notice_args = {
      moderator: user_link(record.moderator),
      time_ago:  time_ago(record.created_at)
  }
%>
<article class="thredded--post-moderation-record thredded--post-moderation-record-<%= record.moderation_state %>">
  <header class="thredded--post-moderation-record--header">
    <p class="thredded--post-moderation-record--moderation-state-notice">
      <% if record.approved? %>
        <%= t('thredded.moderation.post_approved_html', moderation_state_notice_args) %>
      <% elsif record.blocked? %>
        <%= t('thredded.moderation.post_blocked_html', moderation_state_notice_args) %>
      <% end %>
    </p>
    <% if post && post.content != record.post_content %>
      <p class="thredded--post-moderation-record--content-changed-notice">
        <%= t('thredded.moderation.posts_content_changed_since_moderation_html', post_url: post_permalink_path(post)) %>
      </p>
    <% end %>
    <%= content_tag :em, t('thredded.moderation.post_deleted_notice') unless post %>
  </header>
  <article class="thredded--post">
    <% post_user_link = capture do %>
      <% if record.post_user %>
        <%= link_to record.post_user.thredded_display_name, user_moderation_path(record.post_user.id) %>
      <% else %>
        <%= safe_join [record.post_user_name, content_tag(:em, t('thredded.null_user_name'))].compact, ', ' %>
      <% end %>
    <% end %>
    <% if post %>
      <%= render 'thredded/posts_common/header_with_user_and_topic', post: post_view, post_user_link: post_user_link %>
    <% else %>
      <header><h2 class="thredded--post--user"><%= post_user_link %></h2></header>
    <% end %>
    <div class="thredded--post--content">
      <%= Thredded::ContentFormatter.new(self).format_content(record.post_content) %>
    </div>
  </article>
  <%= render 'post_moderation_actions', post: post if post %>
</article>

app/views/thredded/moderation/_user_moderation_state.html.erb
<% user_detail = user.thredded_user_detail %>
<%= user_detail.moderation_state.to_s.humanize %>
<%= time_ago user_detail.moderation_state_changed_at, default: '' %>

app/views/thredded/moderation/_user_post.html.erb
<% post, content = post_and_content if local_assigns.key?(:post_and_content) %>
<%= content_tag :article, id: dom_id(post), class: 'thredded--post thredded--post-moderation' do %>
  <%= render 'thredded/posts_common/actions', post: post %>
  <%= render 'thredded/posts_common/header_with_topic', post: post %>
  <%= content || render('thredded/posts/content', post: post) %>
  <% if post.blocked? %>
    <p class="thredded--alert thredded--alert-danger">
      <%= render 'thredded/shared/content_moderation_blocked_state', moderation_record: post.last_moderation_record %>
    </p>
  <% end %>
  <%= render 'post_moderation_actions', post: post %>
<% end %>

app/views/thredded/moderation/_users_search_form.html.erb
<%= form_tag users_moderation_path,
             method: 'get',
             class: 'thredded--form thredded--navigation--search thredded--navigation--search--right',
             'data-thredded-turboform' => true do %>
  <%= label_tag :q, t('thredded.moderation.search_users.form_label') %>
  <%= text_field_tag :q, @query,
                     type:        'search',
                     required:    true,
                     # If there are no results the user will likely want to change the query, so auto-focus.
                     autofocus:   @query.presence && !@users.presence,
                     placeholder: t('thredded.moderation.search_users.form_placeholder') %>
  <button type="submit"><%= t 'thredded.search.form.btn_submit' %></button>
<% end %>

app/views/thredded/moderation/activity.html.erb
<% content_for :thredded_page_title, t('thredded.nav.moderation') %>
<% content_for :thredded_page_id, 'thredded--moderation-activity' %>
<%= render 'nav' %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <h1><%= t 'thredded.recent_activity' %></h1>
    <% if @last_moderated_record %>
      <div class="thredded--moderated-notice">
        <%= render 'post_moderation_record', post_moderation_record: @last_moderated_record %>
      </div>
    <% end %>
    <% if @posts.present? %>
      <%= render_posts @posts,
                       partial: 'thredded/moderation/post',
                       content_partial: 'thredded/posts/content' %>
      <%= paginate @posts %>
    <% end %>
  </section>
<% end %>

app/views/thredded/moderation/history.html.erb
<% content_for :thredded_page_title,
               safe_join([t('thredded.nav.moderation'), t('thredded.nav.moderation_history')], ': ') %>
<% content_for :thredded_page_id, 'thredded--moderation-history' %>
<%= render 'nav' %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <% if @post_moderation_records.present? %>
      <%= render partial: 'post_moderation_record', collection: @post_moderation_records %>
      <%= paginate @post_moderation_records %>
    <% end %>
  </section>
<% end %>

app/views/thredded/moderation/pending.html.erb
<% content_for :thredded_page_title, t('thredded.nav.moderation') %>
<% content_for :thredded_page_id, 'thredded--pending-moderation' %>
<%= render 'nav' %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <% if @last_moderated_record %>
      <div class="thredded--moderated-notice">
        <%= render 'post_moderation_record', post_moderation_record: @last_moderated_record %>
      </div>
    <% end %>
    <% if @posts.present? %>
      <%= render_posts @posts,
                       partial: 'thredded/moderation/post',
                       content_partial: 'thredded/posts/content' %>
      <%= paginate @posts %>
    <% else %>
      <div class="thredded--empty">
        <h3 class="thredded--empty--title"><%= t 'thredded.moderation.pending.empty.title' %></h3>
        <p><%= t 'thredded.moderation.pending.empty.content' %></p>
      </div>
    <% end %>
  </section>
<% end %>

app/views/thredded/moderation/user.html.erb
<%
  user = @user
  user_detail = user.thredded_user_detail
%>
<% content_for :thredded_page_title, t('thredded.nav.moderation') %>
<% content_for :thredded_page_id, 'thredded--moderation-user' %>
<%= render 'nav' %>
<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= view_hooks.moderation_user_page.user_title.render self, user: user do %>
      <h1 class="thredded--moderation--user--title">
        <%= image_tag Thredded.avatar_url.call(user), class: 'thredded--user--avatar' %><%= user.thredded_display_name %>
      </h1>
    <% end %>
    <%= view_hooks.moderation_user_page.user_info.render self, user: user do %>
      <ul class="thredded--moderation--user--info">
        <%= view_hooks.moderation_user_page.user_info_list_items.render self, user: user do %>
          <li><%= t 'thredded.users.user_since_html', time_ago: time_ago(user.created_at) %></li>
          <% if user_detail.last_seen_at %>
            <li><%= t 'thredded.users.last_active_html', time_ago: time_ago(user_detail.last_seen_at) %></li>
          <% end %>
          <% if user_detail.topics_count > 0 %>
            <li><%= t 'thredded.users.started_topics_count', count: user_detail.topics_count %></li>
          <% end %>
          <% if user_detail.posts_count > 0 %>
            <li><%= t 'thredded.users.posts_count', count: user_detail.posts_count %></li>
          <% end %>
          <li><%= render 'user_moderation_state', user: @user %></li>
        <% end  %>
      </ul>
    <% end %>
    <%= view_hooks.moderation_user_page.user_moderation_actions.render self, user: user do %>
      <div class="thredded--user--moderation-actions">
        <% unless user_detail.approved? %>
          <%= button_to t('thredded.moderation.approve_btn'), moderate_user_path,
                        class: 'thredded--button',
                        params: { id: user.to_model.id, moderation_state: 'approved' } %>
        <% end %>
        <% unless user_detail.blocked? %>
          <%= button_to t('thredded.moderation.block_btn'), moderate_user_path,
                        class: 'thredded--button',
                        params: { id: user.to_model.id, moderation_state: 'blocked' } %>
        <% end %>
      </div>
    <% end %>
    <% if @posts.present? %>
      <h2><%= t 'thredded.users.recent_activity' %></h2>
      <%= render_posts @posts,
                       partial: 'thredded/moderation/user_post',
                       content_partial: 'thredded/posts/content' %>
      <%= paginate @posts %>
    <% end %>
  </section>
<% end %>

app/views/thredded/moderation/users.html.erb
<% content_for :thredded_page_title, t('thredded.nav.moderation') %>
<% content_for :thredded_page_id, 'thredded--moderation-users' %>
<%= render 'nav' %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <% if @users.present? %>
      <% if @query.present? %>
        <p class="thredded--alert thredded--alert-success">
          <%= t 'thredded.moderation.search_users.results_message', query: "'#{@query}'" %>
        </p>
      <% end %>
      <table class="thredded--moderation--users-table thredded--table">
        <caption><%= page_entries_info @users %></caption>
        <thead>
        <tr>
          <th><%= t 'thredded.moderation.user.name' %></th>
          <th><%= t 'thredded.moderation.moderation_state.name' %></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user.thredded_display_name, user_moderation_path(user.id), class: 'thredded--link' %>
            </td>
            <td>
              <%= render 'user_moderation_state', user: user %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    <% else %>
      <p class="thredded--alert thredded--alert-danger">
        <%= t 'thredded.moderation.search_users.no_results_message', query: "'#{@query}'" %>
      </p>
    <% end %>
  </section>
<% end %>