config/routes.rb
# frozen_string_literal: true

Thredded::Engine.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :theme_preview, only: [:show], path: 'theme-preview' if %w[development test].include? Rails.env

  page_constraint = { page: /[1-9]\d*/ }

  scope path: 'private-topics' do
    resource :read_state, only: [:update], as: :mark_all_private_topics_read
    resource :private_topic, only: [:new], path: '' do
      post :preview, on: :new, controller: 'private_topic_previews'
    end
    resources :private_topics, except: %i[new show], path: '' do
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint
      end
      resources :private_posts, path: '', except: %i[index show] do
        post :preview, on: :new, controller: 'private_post_previews'
        resource :preview, only: [:update], controller: 'private_post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  scope only: [:show], constraints: { id: Thredded.routes_id_constraint } do
    resources :private_post_permalinks, path: 'private-posts'
    resources :post_permalinks, path: 'posts'
  end

  resources :autocomplete_users, only: [:index], path: 'autocomplete-users'

  constraints(->(req) { req.env['QUERY_STRING'].include? 'q=' }) do
    get '/' => 'topics#search', as: :messageboards_search
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  scope path: 'admin' do
    resources :messageboard_groups, only: %i[new create]
    scope controller: :moderation, path: 'moderation' do
      scope constraints: page_constraint do
        get '(/page-:page)', action: :pending, as: :pending_moderation
        get '/history(/page-:page)', action: :history, as: :moderation_history
        get '/users(/page-:page)', action: :users, as: :users_moderation
        get '/users/:id(/page-:page)', action: :user, as: :user_moderation
        get '/activity(/page-:page)', action: :activity, as: :moderation_activity
      end
      post '', action: :moderate_post, as: :moderate_post
      post '/user/:id', action: :moderate_user, as: :moderate_user
    end
  end

  resource :preferences, only: %i[edit update], as: :global_preferences
  resource :messageboard, path: 'messageboards', only: [:new]
  resources :messageboards, only: %i[edit update]
  resources :messageboards, only: %i[index create], path: '' do
    resource :preferences, only: %i[edit update]
    resource :topic, path: 'topics', only: [:new] do
      post :preview, on: :new, controller: 'topic_previews'
    end
    resources :topics, path: '', except: %i[index new show] do
      collection do
        get '(page-:page)', action: :index, as: '', constraints: page_constraint
        get '/category/:category_id', action: :category, as: :categories
      end
      member do
        get '(page-:page)', action: :show, as: '', constraints: page_constraint

        # match (un)follow via get as well so that redirecting back to it after sign in works.
        match 'follow', via: %i[post get]
        match 'unfollow', via: %i[post get]
      end
      resources :posts, except: %i[index show], path: '' do
        post :preview, on: :new, controller: 'post_previews'
        resource :preview, only: [:update], controller: 'post_previews'
        member do
          get 'quote'
          post 'mark_as_unread'
        end
      end
    end
  end

  root to: 'messageboards#index'
end

app/models/concerns/thredded/content_moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Moderation state of a piece of content, such as a Thredded::Topic or a Thredded::Post.
  # Requires an integer moderation_state column, a user_id column, and a user_detail association on the including class.
  # @api private
  module ContentModerationState
    extend ActiveSupport::Concern
    include Thredded::ModerationState

    included do
      before_validation :set_default_moderation_state, on: :create

      scope :moderation_state_visible_to_all, -> { where(visible_to_all_arel_node) }

      scope :moderation_state_visible_to_user, (lambda do |user|
        visible = visible_to_all_arel_node
        # @type [Arel::Table]
        table = arel_table
        if user && !user.thredded_anonymous?
          # Own content
          visible = visible.or(table[:user_id].eq(user.id))
          # Content that one can moderate
          moderatable_messageboard_ids = user.thredded_can_moderate_messageboards.map(&:id)
          if moderatable_messageboard_ids.present?
            visible = visible.or(table[:messageboard_id].in(moderatable_messageboard_ids))
          end
        end
        where(visible)
      end)

      # @return [Arel::Nodes::Node]
      # @api private
      def self.visible_to_all_arel_node
        if Thredded.content_visible_while_pending_moderation
          # All non-blocked content
          arel_table[:moderation_state].not_eq(moderation_states[:blocked])
        else
          # Only approved content
          arel_table[:moderation_state].eq(moderation_states[:approved])
        end
      end
    end

    # Whether this is visible to anyone based on the moderation state.
    def moderation_state_visible_to_all?
      if Thredded.content_visible_while_pending_moderation
        !blocked?
      else
        approved?
      end
    end

    # Whether this is visible to the given user based on the moderation state.
    def moderation_state_visible_to_user?(user)
      moderation_state_visible_to_all? ||
        (!user.thredded_anonymous? &&
          (user_id == user.id || user.thredded_can_moderate_messageboards.map(&:id).include?(messageboard_id)))
    end

    private

    def set_default_moderation_state
      self.moderation_state ||= user_detail.moderation_state
    end
  end
end

app/models/concerns/thredded/friendly_id_reserved_words_and_pagination.rb
# frozen_string_literal: true

require 'set'
module Thredded
  # Excludes pagination routes in addition to the given list of reserved words.
  class FriendlyIdReservedWordsAndPagination
    PAGINATION_PATTERN = /\Apage-\d+\z/i

    def initialize(words = [])
      @words = Set.new(words)
    end

    def include?(slug)
      @words.include?(slug) || slug =~ PAGINATION_PATTERN
    end
  end
end

app/models/concerns/thredded/moderation_state.rb
# frozen_string_literal: true

module Thredded
  # Defines a moderation_state enum
  # Requires an integer moderation_state column on the including class.
  module ModerationState
    extend ActiveSupport::Concern

    included do
      enum moderation_state: %i[pending_moderation approved blocked]
      validates :moderation_state, presence: true
    end
  end
end

app/models/concerns/thredded/notifier_preference.rb
# frozen_string_literal: true

module Thredded
  module NotifierPreference
    extend ActiveSupport::Concern

    included do
      delegate :human_name, to: :notifier, prefix: true

      def self.detect_or_default(prefs, notifier)
        (prefs && prefs.find { |pref| pref.notifier_key == notifier.key }) || default(notifier)
      end
    end

    def notifier
      @notifier ||= Thredded.notifiers.find { |notifier| notifier.key == notifier_key }
    end
  end
end

app/models/concerns/thredded/post_common.rb
# frozen_string_literal: true

module Thredded
  # @abstract Classes that include this module are expected to implement {#readers}.
  # @!method readers
  #     @abstract
  #     @return [ActiveRecord::Relation<Thredded.user_class>] users from that can read this post.
  module PostCommon
    extend ActiveSupport::Concern

    included do
      paginates_per 50

      delegate :email, to: :user, prefix: true, allow_nil: true

      validates :content, presence: true

      scope :order_oldest_first, -> { order(created_at: :asc, id: :asc) }
      scope :order_newest_first, -> { order(created_at: :desc, id: :desc) }

      before_validation :ensure_user_detail, on: :create
    end

    def avatar_url
      Thredded.avatar_url.call(user)
    end

    def calculate_page(postable_posts, per_page)
      1 + postable_posts.where(postable_posts.arel_table[:created_at].lt(created_at)).count / per_page
    end

    # @param view_context [Object] the context of the rendering view.
    # @return [String] formatted and sanitized html-safe post content.
    def filtered_content(view_context, users_provider: ->(names) { readers_from_user_names(names) }, **options)
      Thredded::ContentFormatter.new(view_context, users_provider: users_provider, **options).format_content(content)
    end

    def first_post_in_topic?
      postable.first_post == self
    end

    # @return [ActiveRecord::Relation<Thredded.user_class>] users from the list of user names that can read this post.
    # @api private
    def readers_from_user_names(user_names)
      DbTextSearch::CaseInsensitive
        .new(readers, Thredded.user_name_column)
        .in(user_names)
    end

    # Marks all the posts from the given one as unread for the given user
    # @param user [Thredded.user_class]
    # @param page [Integer]
    def mark_as_unread(user, page)
      if previous_post.nil?
        read_state = postable.user_read_states.find_by(user_id: user.id)
        read_state.destroy if read_state
      else
        read_state = postable.user_read_states.create_with(
          read_at: previous_post.created_at,
          page: page
        ).find_or_create_by(user_id: user.id)
        read_state.update_columns(read_at: previous_post.created_at, page: page)
      end
    end

    def previous_post
      @previous_post ||= postable.posts.order_newest_first.find_by('created_at < ?', created_at)
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end
  end
end

app/models/concerns/thredded/search_parser.rb
# frozen_string_literal: true

module Thredded
  class SearchParser
    def initialize(query)
      @query = query
      @keywords = %w[in by order]
    end

    def parse
      parsed_input = parse_keywords
      parsed_input['text'] = parse_text
      parsed_input
    end

    def parse_keywords
      found_terms_hash = {}

      @keywords.each do |keyword|
        regex = Regexp.new(keyword + '\s*:\s*\w+', Regexp::IGNORECASE)
        keyword_scan = @query.scan(regex)
        @query = @query.gsub(regex, '')

        next if keyword_scan.blank?
        keyword_scan.each do |term|
          found_terms_hash[keyword] ||= []
          found_terms_hash[keyword] << term.delete(' ').split(':')[1]
        end
      end

      found_terms_hash
    end

    def parse_text
      regex = Regexp.new('\"[^"]*\"')
      found_terms = @query.scan(regex)
      @query = @query.sub(regex, '')
      found_terms.concat(@query.split(/\s+/))
    end
  end
end

app/models/concerns/thredded/topic_common.rb
# frozen_string_literal: true

module Thredded
  module TopicCommon
    extend ActiveSupport::Concern
    included do
      paginates_per 50 if respond_to?(:paginates_per)

      belongs_to :last_user,
                 class_name: Thredded.user_class_name,
                 foreign_key: 'last_user_id',
                 **(Thredded.rails_gte_51? ? { optional: true } : {})

      scope :order_recently_posted_first, -> { order(last_post_at: :desc, id: :desc) }
      scope :on_page, ->(page_num) { page(page_num) }

      validates :hash_id, presence: true, uniqueness: true
      validates :posts_count, numericality: true

      before_validation do
        self.hash_id = SecureRandom.hex(10) if hash_id.nil?
      end

      delegate :name, :name=, :email, :email=, to: :user, prefix: true

      before_validation :ensure_user_detail, on: :create
    end

    def user
      super || Thredded::NullUser.new
    end

    def last_user
      super || Thredded::NullUser.new
    end

    def private?
      !public?
    end

    private

    def ensure_user_detail
      build_user_detail if user && !user_detail
    end

    module ClassMethods
      # @param user [Thredded.user_class]
      # @return [ActiveRecord::Relation]
      def unread(user)
        topics      = arel_table
        reads_class = reflect_on_association(:user_read_states).klass
        reads       = reads_class.arel_table
        joins(topics.join(reads, Arel::Nodes::OuterJoin)
                .on(topics[:id].eq(reads[:postable_id]).and(reads[:user_id].eq(user.id))).join_sources)
          .merge(reads_class.where(reads[:id].eq(nil).or(reads[:read_at].lt(topics[:last_post_at]))))
      end

      private

      # @param user [Thredded.user_class]
      # @return [ByPostableLookup]
      def read_states_by_postable_hash(user)
        read_states = reflect_on_association(:user_read_states).klass
          .where(user_id: user.id, postable_id: current_scope.map(&:id))
        Thredded::TopicCommon::CachingHash.from_relation(read_states)
      end

      public

      # @param user [Thredded.user_class]
      # @return [Array<[TopicCommon, UserTopicReadStateCommon]>]
      def with_read_states(user)
        null_read_state = Thredded::NullUserTopicReadState.new
        return current_scope.zip([null_read_state]) if user.thredded_anonymous?
        read_states_by_postable = read_states_by_postable_hash(user)
        current_scope.map do |postable|
          [postable, read_states_by_postable[postable] || null_read_state]
        end
      end
    end

    class CachingHash < Hash
      def self.from_relation(postable_relation)
        self[postable_relation.map { |related| [related.postable_id, related] }]
      end

      # lookup related item by postable and set the inverse lookup
      def [](postable)
        super(postable.id).tap { |related| related.postable = postable if related }
      end
    end
  end
end

app/models/concerns/thredded/topics_search.rb
# frozen_string_literal: true

module Thredded
  class TopicsSearch
    def initialize(query, scope)
      @terms = Thredded::SearchParser.new(query).parse
      @scope = scope

      @search_categories = @search_users = @search_text = nil
    end

    # @return [ActiveRecord::Relation<Thredded::Topic>]
    def search
      if categories.present?
        @scope = @scope.joins(:topic_categories).merge(Thredded::TopicCategory.where(category_id: categories))
      end
      if text.present? || users.present?
        [search_topics, search_posts].compact.reduce(:union)
      else
        @scope
      end
    end

    protected

    def search_topics
      scope = @scope
      scope = @scope.where(user_id: users) if users.present?
      scope = DbTextSearch::FullText.new(scope, :title).search(text) if text.present?
      scope
    end

    def search_posts
      posts_scope = Thredded::Post
      posts_scope = posts_scope.where(user_id: users) if users.present?
      posts_scope = DbTextSearch::FullText.new(posts_scope, :content).search(text) if text.present?
      @scope.joins(:posts).merge(posts_scope)
    end

    def categories
      @search_categories ||=
        if @terms['in'].present?
          DbTextSearch::CaseInsensitive
            .new(Category, :name)
            .in(@terms['in']).pluck(:id)
        else
          []
        end
    end

    def users
      @search_users ||=
        if @terms['by']
          DbTextSearch::CaseInsensitive
            .new(Thredded.user_class, Thredded.user_name_column)
            .in(@terms['by']).pluck(:id)
        else
          []
        end
    end

    # @return [Array<String>]
    def text
      @terms['text']
    end
  end
end

app/models/concerns/thredded/user_topic_read_state_common.rb
# frozen_string_literal: true

module Thredded
  module UserTopicReadStateCommon
    extend ActiveSupport::Concern
    included do
      extend ClassMethods
      validates :user_id, uniqueness: { scope: :postable_id }
    end

    # @return [Boolean]
    def read?
      postable.last_post_at <= read_at
    end

    # @param post [Post or PrivatePost]
    # @return [Boolean]
    def post_read?(post)
      post.created_at <= read_at
    end

    module ClassMethods
      # @param user_id [Integer]
      # @param topic_id [Integer]
      # @param post [Thredded::PostCommon]
      # @param post_page [Integer]
      def touch!(user_id, topic_id, post, post_page)
        # TODO: Switch to upsert once Travis supports PostgreSQL 9.5.
        # Travis issue: https://github.com/travis-ci/travis-ci/issues/4264
        # Upsert gem: https://github.com/seamusabshere/upsert
        state = find_or_initialize_by(user_id: user_id, postable_id: topic_id)
        fail ArgumentError, "expected post_page >= 1, given #{post_page.inspect}" if post_page < 1
        return unless !state.read_at? || state.read_at < post.created_at
        state.update!(read_at: post.created_at, page: post_page)
      end

      def read_on_first_post!(user, topic)
        create!(user: user, postable: topic, read_at: Time.zone.now, page: 1)
      end
    end
  end
end

app/models/thredded/category.rb
# frozen_string_literal: true

module Thredded
  class Category < ActiveRecord::Base
    extend FriendlyId
    belongs_to :messageboard
    has_many :topic_categories
    has_many :topics, through: :topic_categories
    friendly_id :name, use: %i[history scoped], scope: :messageboard

    validates :name, presence: true
    validates :messageboard_id, presence: true

    def normalize_friendly_id(input)
      Thredded.slugifier.call(input.to_s)
    end
  end
end

app/models/thredded/null_user_topic_read_state.rb
# frozen_string_literal: true

module Thredded
  class NullUserTopicReadState
    def page
      1
    end

    def read?
      false
    end

    def post_read?(_post)
      false
    end
  end
end

app/views/thredded/private_topics/_breadcrumbs.html.erb
<ul class="thredded--navigation-breadcrumbs">
  <li><%= link_to t('thredded.nav.all_messageboards'), messageboards_path -%></li>
  <li><%= link_to t('thredded.nav.private_topics'), private_topics_path -%></li>
</ul>

app/views/thredded/private_topics/_form.html.erb
<%= form_for private_topic,
             url: private_topic.submit_path,
             html: {
                 class: "thredded--form thredded--new-private-topic-form #{local_assigns[:css_class]}",
                 'data-thredded-topic-form' => true,
                 # TODO: only autocomplete users in this private topic
                 'data-autocomplete-url' => autocomplete_users_path,
                 'data-autocomplete-min-length' => Thredded.autocomplete_min_length,
             } do |form| %>

  <ul class="thredded--form-list on-top">
    <li class="title">
      <%= form.label :title, t('thredded.private_topics.form.title_label') %>
      <%= form.text_field :title, placeholder: placeholder, required: true %>
    </li>
    <li>
      <%= form.label :user_names, t('thredded.private_topics.form.users_label') %>
      <%= form.text_area :user_names,
                         placeholder: t('thredded.private_topics.form.users_placeholder'),
                         'data-thredded-users-select' => true,
                         'data-autocomplete-url' => autocomplete_users_path,
                         'data-autocomplete-min-length' => Thredded.autocomplete_min_length,
                         rows: 1 %>
    </li>

    <%= render 'thredded/posts_common/form/content',
               form: form,
               content_label: t('thredded.private_topics.form.content_label'),
               preview_url: private_topic.preview_path %>

    <li>
      <button type="submit" class="thredded--form--submit"
              data-disable-with="<%= t 'thredded.private_topics.form.create_btn_submitting' %>">
        <%= t('thredded.private_topics.form.create_btn') %>
      </button>
    </li>
  </ul>
<% end %>

app/views/thredded/private_topics/_header.html.erb
<header class="thredded--topic-header">
  <h1 class="thredded--topic-header--title"><%= topic.title %></h1>
  <cite class="thredded--topic-header--started-by">
    <%= t 'thredded.topics.started_by_html',
          time_ago: time_ago(topic.created_at),
          user:     user_link(topic.user) %>
  </cite>
  <span class="thredded--topic-header--participants">
    <%= render partial: 'thredded/private_topics/header/participant',
               collection: (topic.users - [topic.user]) %>
  </span>
  <% if topic.can_update? %>
    <%= link_to t('thredded.private_topics.edit'), topic.edit_path,
                class: 'thredded--topic-header--edit-topic',
                rel: 'nofollow' %>
  <% end %>
</header>

app/views/thredded/private_topics/_no_private_topics.html.erb
<div class="thredded--empty">
  <h3 class="thredded--empty--title"><%= t 'thredded.private_topics.no_private_topics.title' %></h3>
  <a class="thredded--button" href="<%= new_private_topic_path %>">
    <%= t 'thredded.private_topics.no_private_topics.create_btn' %>
  </a>
</div>

app/views/thredded/private_topics/_private_topic.html.erb
<%= content_tag :article,
                id: dom_id(private_topic),
                class: ['thredded--topics--topic', *topic_css_classes(private_topic)] do %>
  <div class="thredded--topics--posts-count"><%= private_topic.posts_count %></div>

  <h1 class="thredded--topics--title">
    <%= link_to private_topic.title, private_topic.path %>
  </h1>

  <cite class="thredded--topics--updated-by">
    <%= time_ago private_topic.last_post_at %>
    <span class="thredded--topics--participants">
      <%= render partial: 'thredded/private_topics/private_topic/participant',
                 collection: [private_topic.last_user, *(private_topic.users - [private_topic.last_user])] %>
    </span>
  </cite>

  <cite class="thredded--topics--started-by">
    <%= time_ago private_topic.created_at %>
    <%= user_link private_topic.user %>
  </cite>
<% end %>

app/views/thredded/private_topics/edit.html.erb
<% content_for :thredded_page_title, t('thredded.nav.edit_private_topic') %>
<% content_for :thredded_page_id, 'thredded--edit-private-topic' %>
<% content_for :thredded_breadcrumbs do %>
  <ul class="thredded--navigation-breadcrumbs">
    <li><%= link_to t('thredded.nav.all_messageboards'), messageboards_path %></li>
    <li><%= link_to t('thredded.nav.private_topics'), private_topics_path %></li>
    <li><%= link_to @private_topic.title, topic_path(@private_topic) %></li>
    <li><%= link_to t('thredded.nav.edit_private_topic'), edit_private_topic_path(@private_topic) %></li>
  </ul>
<% end %>


<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= form_for @private_topic,
                 url: private_topic_path(@private_topic),
                 html: { class: 'thredded--form', 'data-thredded-topic-form' => true } do |form| %>
      <ul class="thredded--form-list on-top">
        <li class="title">
          <%= form.label :title, t('thredded.private_topics.form.title_label') %>
          <%= form.text_field :title,
                              placeholder: t('thredded.private_topics.form.title_placeholder_new'),
                              autofocus: true,
                              required: true %>
        </li>
        <li>
          <button type="submit" class="thredded--form--submit"
                  data-disable-with="<%= t 'thredded.private_topics.form.update_btn_submitting' %>">
            <%= t('thredded.private_topics.form.update_btn') %>
          </button>
        </li>
      </ul>
    <% end %>
  </section>
<% end %>

app/views/thredded/private_topics/index.html.erb
<% content_for :thredded_page_title, t('thredded.nav.private_topics') %>
<% content_for :thredded_page_id, 'thredded--private-topics-index' %>
<% content_for :thredded_breadcrumbs, render('thredded/private_topics/breadcrumbs') %>

<%= thredded_page do %>
  <%= content_tag :section,
    class: 'thredded--main-section thredded--private-topics',
    'data-thredded-topics' => true do %>

    <% if @private_topics.empty? -%>
      <%= render 'thredded/private_topics/no_private_topics' %>
    <% else -%>
      <%= render 'thredded/private_topics/form',
                 private_topic: @new_private_topic,
                 css_class: 'thredded--is-compact',
                 placeholder: t('thredded.private_topics.form.title_placeholder_start') if @new_private_topic %>

      <%= render @private_topics %>

      <% unless unread_private_topics_count.zero? %>
        <%= link_to t('thredded.nav.mark_all_read'),
                    mark_all_private_topics_read_path,
                    class: 'thredded--button thredded--button-light thredded--button-wide',
                    method: :put -%>
      <% end %>
    <% end -%>
  <% end %>

  <footer class="thredded--pagination-bottom">
    <%= paginate @private_topics %>
  </footer>
<% end %>

app/views/thredded/private_topics/new.html.erb
<% content_for :thredded_page_title, t('thredded.private_topics.create') %>
<% content_for :thredded_page_id, 'thredded--new-private-topic' %>
<% content_for :thredded_breadcrumbs, render('thredded/private_topics/breadcrumbs') %>

<%= thredded_page do %>
  <section class="thredded--main-section">
    <%= render 'thredded/private_topics/form',
               private_topic: @private_topic,
               placeholder:   t('thredded.private_topics.form.title_placeholder_new') if @private_topic %>
  </section>
<% end %>

app/views/thredded/private_topics/show.html.erb
<% private_topic = @posts.topic %>
<% content_for :thredded_page_title, private_topic.title %>
<% content_for :thredded_page_id, 'thredded--private-topic-show' %>
<% content_for :thredded_breadcrumbs, render('thredded/private_topics/breadcrumbs') %>

<%= thredded_page do %>
  <%= content_tag :section,
                  id: dom_id(private_topic),
                  class: ['thredded--main-section', 'thredded--topic', *topic_css_classes(private_topic)] do %>
    <%= render 'thredded/private_topics/header', topic: private_topic %>
    <%= view_hooks.posts_common.pagination_top.render(self, posts: @posts) do %>
      <footer class="thredded--pagination-top"><%= paginate @posts %></footer>
    <% end %>
    <%= render_posts @posts,
                     partial: 'thredded/private_posts/private_post',
                     content_partial: 'thredded/private_posts/content',
                     locals: { actions: { quote: true } }  %>
    <%= view_hooks.posts_common.pagination_bottom.render(self, posts: @posts) do %>
      <footer class="thredded--pagination-bottom"><%= paginate @posts %></footer>
    <% end %>

    <% if policy(@new_post.post).create? %>
      <%= render 'thredded/private_posts/form',
               topic: private_topic,
               post: @new_post %>
    <% end %>
  <% end %>
<% end %>